---
#file: site.yml
#Master playbook for MySQL replication

- name: common configuration
  hosts: all
  user: root

  roles:
    - common

- name: configure master
  hosts: dbmaster
  user: root

  roles:
    - master

- name: configure slave
  hosts: dbslave
  user: root

  roles:
    - slave