---
#file: roles/master/tasks/main.yml

- name: master database config update
  template: >
    src=my.cnf.j2
    dest=/etc/my.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mysql

- name: replication user setup
  mysql_user: >
    name={{ replication_user }}
    host=%
    password={{ replication_password }}
    priv=*.*:"REPLICATION CLIENT,SUPER,SELECT,RELOAD"
    state=present

- name: test data copy
  copy: src=/tmp/fullbackup.sql.gz dest=/tmp/fullbackup.sql.gz mode=0644

- name: test data unpack
  command: gunzip /tmp/fullbackup.sql.gz

- name: test data import
  shell: mysql < /tmp/fullbackup.sql  

- name: backup cron setup
  cron: >
    special_time=daily
    name="db backup"
    job="/usr/bin/mysqldump --single-transaction --master-data --all-databases -u{{ replication_user }} -p{{ replication_password }} > {{ backup_path }}"
    state=present

- name: initial backup
  shell: /usr/bin/mysqldump --single-transaction --master-data --all-databases -u{{ replication_user }} -p{{ replication_password }} > {{ backup_path }}

  #creates={{ backup_path }}

- name: backup fetch
  fetch: src={{ backup_path }} dest=/tmp/ flat=yes